### ISSUE TITLE
Face_Recognition

### ISSUE THREAD

**Issue by abhishekju06** [ahmedfgad/KivyAndroidClassification#1]
Hi,

If I want to use face recognition with Kivy which library should I use? For face_recognition library I am facing a dlib modulenot founderror in python for android. Please suggest me.

**Comment by ahmedfgad** [comment]
Hi,

Please note that there is a limited number of Python libraries supported in Android. You may try using OpenCV in Android despite it is very error-prone!

A backup strategy I suggest is to build the face recognition system on a server and access it from the Android app. 

Please let me know if I can help!
